modLoader = "javafml" #mandatory
loaderVersion = "[45,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"

[[mods]] #mandatory
modId = "sleep_in_darkness" #mandatory
version = "1.19.4-1.20.1-1.1.0" #mandatory
displayName = "Sleep In Darkness" #mandatory
logoFile="sleep_in_darkness.png" #optional
authors="ISenseHostility" #optional
description = '''
Makes you unable to sleep in a bright environment.
'''

[[dependencies.sleep_in_darkness]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"

[[dependencies.sleep_in_darkness]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,)"
ordering="NONE"
side="BOTH"
